fix: update gnonative API (#179)
This PR fixes an issue when you want to execute `npm install` in the
`expo` folder, that fails with this error:

```bash
src/api/GnoNativeApi.ts:249:91 - error TS2561: Object literal may only specify known properties, but 'addresses' does not exist in type 'PartialMessage<UpdatePasswordRequest>'. Did you mean to write 'address'?

249     const response = await client.updatePassword(new UpdatePasswordRequest({ newPassword, addresses }));
```

It's because we need to update the `gnonative` API that implements the
new addresses field in the request.

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>